### ISSUE TITLE
Create new GitHub issues to plan and track changes from second half of component audit

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-pattern-library#69]
Part 2 of #47  — To be created from patterns audited in #67

After auditing the remaining half of the components in #67 , create new github issues that identify actions needed for getting each component up to date.

- [ ] Identify list of components (copied from #67 )
- [ ] If a new issue is needed, file one for each component listed

**Comment by jenniferthibault** [comment]
Tracking next steps for the following components:

- [x] Icon headings - addressed through #80 
- [ ] Messages: needs new issues
- [x] Option components - addressed through #80 
- [x] Overlay - addressed through #80 
- [ ] Pagination: needs new issues 
- [ ] Reaction box - partially addressed through #80,  new issue to be filed
- [x] Side nav - addressed through #80 
- [x] Sidebar - addressed through #80 
- [x] Slabs - addressed through #80 
- [ ] Tables: needs new issues
- [x] Tags - addressed through #80 
- [x] Tooltips - partially addressed through #80,  new issue to be filed
